version: "3.1"
services:
  mysql:
    image: mysql:5.7.16
    container_name: db
    tty: true
    restart: unless-stopped
    env_file: .env
    working_dir: /application
    volumes:
      - data:/var/lib/mysql/
    ports:
      - "8002:3306"
    networks:
      - email-service-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/application
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - email-service-network

  php:
    build:
      context: ./compose/php
      dockerfile: Dockerfile
    container_name: email
    working_dir: /application
    ports:
      - "9000:9000"
    volumes:
      - .:/application
      - ./compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - email-service-network

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/application
    working_dir: /application
    depends_on:
      - php
    networks:
      - email-service-network

  artisan:
    build:
      context: ./compose/php
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - .:/application
    depends_on:
      - mysql
    working_dir: /application
    entrypoint: ['php', '/application/artisan']
    networks:
      - email-service-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8183:80"
    networks:
      - email-service-network

networks:
  email-service-network:

volumes:
  data:
    driver: local